server.port=8080
server.servlet.context-path=/api/v1

spring.application.name=EcommerceSpringBoot

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=50MB

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=ecommerce
spring.datasource.password=ecommerce
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

uploads.product= /home/chamreunvira/Desktop/EcommerSpringBoot/uploads/product

jwt.secretBase64=cGxheXdpc2VkZWNpZGVlbmpveWZhY3RvcndhaXRtZW1iZXJwYXBlcnRhc2twbGVhc3U=
jwt.expiration=4672000